services:
  app:
    container_name: app
    image: ${IMAGE_TAG}
    restart: always
    expose:
      - 3000

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: 'unless-stopped'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    ports:
      - '80:80'
      - '443:443'

  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;"

volumes:
  certbot-etc:
  certbot-var:
