services:
  app:
    container_name: app
    image: ${IMAGE_TAG}
    restart: always
    env_file:
      - .env
    expose:
      - 3000

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: 'unless-stopped'
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - '80:80'
      - '443:443'

  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
